### ISSUE TITLE
Feature request: Inline display of the GR

### ISSUE THREAD

**Issue by magnetophon** [magnetophon/molot-lite#11]
Ardour (and possibly others) can display graphics in the plugin section of the mixer screen.
It is often used to show GR in a dynamics processor.

It would be very handy if molot-lite could do the same.
A simple one would be ideal, imho; like this:
https://user-images.githubusercontent.com/30246/136995910-ed9f6b19-7b28-419f-8ee5-2f9675bec4c4.gif

Thanks for considering!

**Comment by jpcima** [comment]
Hm yes I think we can have that.

**Comment by magnetophon** [comment]
Implemented in PR #12.
